module.exports = {
  apps: [
    {
      name: "api-gateway",
      cwd: "./api-gateway",
      script: "./dist/main.js",
      autorestart: true,
      env: {
        NODE_ENV: "development",
        AUTH_SERVICE_BASE_URL: "http://localhost:3001",
        ORDER_SERVICE_BASE_URL: "http://localhost:3002",
        PRODUCT_SERVICE_BASE_URL: "http://localhost:3003",
        SELLER_SERVICE_BASE_URL: "http://localhost:3004",
        PORT: 3000,
      },
      env_production: {
        JWT_SECRET: "INJECT_JWT_SECRET",
        NODE_ENV: "production",
        AUTH_SERVICE_BASE_URL: "INJECT_AUTH_SERVICE_BASE_URL",
        PRODUCT_SERVICE_BASE_URL: "INJECT_PRODUCT_SERVICE_BASE_URL",
        PORT: "INJECT_GATEWAY_PORT",
        ORDER_SERVICE_BASE_URL: "INJECT_ORDER_SERVICE_BASE_URL",
        ALLOWED_ORIGINS: "INJECT_ALLOWED_ORIGINS",
      },
      time: true,
    },
    {
      name: "auth-service",
      cwd: "./auth-service",
      script: "./dist/main.js",
      autorestart: true,
      env: {
        NODE_ENV: "development",
        PORT: 3001,
      },
      env_production: {
        NODE_ENV: "production",
        JWT_SECRET: "INJECT_JWT_SECRET",
        OTP_EXPIRY_DURATION: "INJECT_OTP_EXPIRY_DURATION",
        MAIL_HOST: "INJECT_MAIL_HOST",
        MAIL_PORT: "INJECT_MAIL_PORT",
        MAIL_USERNAME: "INJECT_MAIL_USERNAME",
        MAIL_PASSWORD: "INJECT_MAIL_PASSWORD",
        MAIL_FROM: "INJECT_MAIL_FROM",
        FRONTEND_URL: "INJECT_FRONTEND_URL",

        GOOGLE_CLIENT_ID: "INJECT_GOOGLE_CLIENT_ID",
        GOOGLE_CLIENT_SECRET: "INJECT_GOOGLE_CLIENT_SECRET",
        GOOGLE_CALLBACK_URL: "INJECT_GOOGLE_CALLBACK_URL",

        FACEBOOK_APP_ID: "INJECT_FACEBOOK_APP_ID",
        FACEBOOK_APP_SECRET: "INJECT_FACEBOOK_APP_SECRET",
        FACEBOOK_CALLBACK_URL: "INJECT_FACEBOOK_CALLBACK_URL",

        EMAIL_ENCRYPTION_KEY: "INJECT_EMAIL_ENCRYPTION_KEY",

        SALT_ROUND: "INJECT_SALT_ROUND",
        PORT: "INJECT_AUTH_PORT",
        DATABASE_URL_DEV_USERS: "INJECT_DATABASE_URL_DEV_USERS",
        DNS: "INJECT_DNS",
      },
      time: true,
    },
    {
      name: "product-service",
      cwd: "./product-service",
      script: "./dist/main.js",
      autorestart: true,
      env: {
        NODE_ENV: "development",
        PORT: 3003,
      },
      env_production: {
        NODE_ENV: "production",
        JWT_SECRET: "INJECT_JWT_SECRET",
        USER_SERVICE_URL: "INJECT_USER_SERVICE_URL",
        PORT: "INJECT_PRODUCT_PORT",
        DATABASE_URL_DEV_PRODUCT: "INJECT_DATABASE_URL_DEV_PRODUCT",
        HASHIDS_SALT: "INJECT_HASHIDS_SALT",
      },
      time: true,
    },
    {
      name: "order-service",
      cwd: "./order-service",
      script: "./dist/main.js",
      autorestart: true,
      env: {
        NODE_ENV: "development",
        PORT: 3002,
      },
      env_production: {
        NODE_ENV: "production",
        JWT_SECRET: "INJECT_JWT_SECRET",
        PORT: "INJECT_ORDER_PORT",
        AUTH_SERVICE_URL: "INJECT_AUTH_SERVICE_URL",
        PRODUCT_SERVICE_URL: "INJECT_PRODUCT_SERVICE_URL",
        DATABASE_URL_DEV_ORDER: "INJECT_DATABASE_URL_DEV_ORDER",
        HASHIDS_SALT: "INJECT_HASHIDS_SALT",
        STRIPE_SECRET_KEY: "INJECT_STRIPE_SECRET_KEY",
        STRIPE_WEBHOOK_SECRET: "INJECT_STRIPE_WEBHOOK_SECRET",
        STRIPE_CONNECT_ACCOUNT_ID: "INJECT_STRIPE_CONNECT_ACCOUNT_ID",
        STRIPE_ONBOARDING_REFRESH_URL: "INJECT_STRIPE_ONBOARDING_REFRESH_URL",
        STRIPE_ONBOARDING_RETURN_URL: "INJECT_STRIPE_ONBOARDING_RETURN_URL",
        FEDEX_CLIENT_ID: "INJECT_FEDEX_CLIENT_ID",
        FEDEX_CLIENT_SECRET: "INJECT_FEDEX_CLIENT_SECRET",
        FEDEX_ACCOUNT_NUMBER: "INJECT_FEDEX_ACCOUNT_NUMBER",
        FEDEX_METER_NUMBER: "INJECT_FEDEX_METER_NUMBER",
        FEDEX_API_BASE_URL: "INJECT_FEDEX_API_BASE_URL",
        FEDEX_OAUTH_URL: "INJECT_FEDEX_OAUTH_URL",
        FEDEX_IS_PRODUCTION: "INJECT_FEDEX_IS_PRODUCTION",
      },
      time: true,
    },
  ],
};
