export enum GlobalConfigKeys {
  PRODUCT_VIEWERSHIP_LAST_SEEN = 'PRODUCT_VIEWERSHIP_LAST_SEEN',
  SEED_SCRIPT_RUN = 'SEED_SCRIPT_RUN',
  NEW_ARRIVAL = 'NEW_ARRIVAL',
  POPULAR = 'POPULAR',
  BEST_SELLER = 'BEST_SELLER',
}
